<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21878" started-at="2020-08-25T10:58:53Z" finished-at="2020-08-25T10:59:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21878" started-at="2020-08-25T10:58:53Z" finished-at="2020-08-25T10:59:15Z">
      <class name="TestCases.updateCustomerInfo">
        <test-method status="FAIL" signature="updateCustomerInfoCheck()[pri:0, instance:TestCases.updateCustomerInfo@3967e60c]" name="updateCustomerInfoCheck" duration-ms="21675" started-at="2020-08-25T11:58:53Z" finished-at="2020-08-25T11:59:15Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at TestCases.updateCustomerInfo.updateCustomerInfoCheck(updateCustomerInfo.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateCustomerInfoCheck -->
        <test-method status="PASS" signature="closePage()[pri:0, instance:TestCases.updateCustomerInfo@3967e60c]" name="closePage" is-config="true" duration-ms="180" started-at="2020-08-25T11:59:15Z" finished-at="2020-08-25T11:59:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closePage -->
      </class> <!-- TestCases.updateCustomerInfo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
